### ISSUE TITLE
Criar funcionalidade no WeeDraw para ler uma pasta e avaliar marcações

### ISSUE THREAD

**Issue by hericlesferraz** [sensixag/weedraw#11]
Selecionar pasta, que já está no formato gerado pelo WeeDraw, para avaliar as marcações feitas sobre cada path.

**Comment by hericlesferraz** [comment]
#### Descrição
Inserir analise de marcações efetuadas, carregando a imagem RGB e a imagem binária efetuada a partir da documentação.

Visualização da marcação efetuada anteriormente, utillizando-se o mesmo padrão de interface, considerando-se a criação das marcações.
![Imagem Nome](https://user-images.githubusercontent.com/65249438/161297768-d4952a35-e87f-4c7f-a80a-6330a75f8a77.png)

#### Tasks
Subtarefas que estão inseridas dentro da issue atual
- [x] Adicionar opção no menu para analisar marcações efetuadas
- [x] Opção de analisar a marcação, utilizando-se como referência a imagem RGB. 
- [x] Opção de modificar a marcação efetuada anteriormente
- [ ] Inserir opção de visualização da marcação já efetuada por contornos ou com preenchimentos
