### ISSUE TITLE
Inserir caixa de zoom para marcação mais precisa

### ISSUE THREAD

**Issue by hericlesferraz** [sensixag/weedraw#15]
#### Descrição
Inserir opção de zoom no WeeDraw, para facilitar a visualização das marcações efetuadas, de forma que o zoom e a marcação nas imagens estejam centralizadas.

#### Imagens
![weedraw_zoom](https://user-images.githubusercontent.com/65249438/164741926-ff5171f5-546e-4b75-a265-eb33ccdbb602.gif)

#### Tasks
Subtarefas  inseridas dentro desta issue:
- [x] Tratativas para gastar menos memoria ram
- [x] Configurações para o zoom não ser acionado fora da area da imagem
- [x] Opção de mover arrastar imagem com o zoom
- [x] Inserir movimentação utilizando teclas [A,W,S,D]
- [x] Estabelecer controle de fluxo entre as callbacks de desenho e as de zoom
- [x] Calcular a influência de cada um dos corners, para cada tipo distinto de área correspondente ao  zoom 
- [x] Centralizar marcação de desenho, para que o desenho efetuado esteja em cima da secção de zoom
- [x] Deixar o zoom out normalizado para recentralizar a visualização após a utilização de um zoom in

**Comment by hericlesferraz** [comment]
#### Descrição
Informações adicionais a respeito da tarefa de organizar os corners.

#### Imagens
Imagem que apresenta a construção estrutural dos cornes.
![autodraw 4_29_2022](https://user-images.githubusercontent.com/65249438/165953464-8f632f95-4daf-4051-a94e-d43060c2b3f2.png)

Funcionamento do sistema.
![weedraw_zoom_and_draw_2](https://user-images.githubusercontent.com/65249438/165956299-88449cbd-fb19-49ff-ac57-ad1663c2db15.gif)
