### ISSUE TITLE
Criar programa paralelo ao WeeDraw para verificação de marcações efetuadas.

### ISSUE THREAD

**Issue by hericlesferraz** [sensixag/weedraw#28]
#### Descrição
Criar um programa paralelo ao WeeDraw, com uma execução.exe, e que serve para validar os labels que já foram criados.

#### Imagens
![analiser](https://user-images.githubusercontent.com/65249438/169527203-df249464-f2eb-4871-a5ea-0ead6440a3b6.gif)

#### Tasks
Subtarefas que estão inseridas dentro da issue atual
- [x] Criar programa novo simplificado, sem utilização de gdal e bibliotecas de machine learning
- [x] Inserir ferramentas necessárias para verificação dos labels efetuados
- [x] Inserir opção de efetuar-se a analise entre o label e a imagem 
- [x] Inserir opção de modificar-se o label e salvar-se a modificação efetuada
- [x] Inserir oplções padrões do WeeDraw original, como zoom e saturação 
- [x] Gerar executável para rodar de forma independente das instalações locais
