### ISSUE TITLE
Adicionar atalhos no teclado equivalentes aos cliques sobre os botões no WeeDraw, como opção de trocar de imagens via setas direcionais, tecla selecionada que habilita função de desenhar.

### ISSUE THREAD

**Issue by betoecd** [sensixag/weedraw#37]
#### Descrição
Adição de keys para diminuir o número de clickes no momento da marcação

#### Tasks
Subtarefas que estão inseridas dentro da issue atual
- [x] Teclas de transições de imagens, utilizando teclas: (A,D)
- [x] Teclas para cada um dos botões, 0 para lapis, 1 poligono, 2 borracha, até a tecla 5.
- [x] botão esquerdo do mouse pressionado
